# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import py_protos.detection_v2_pb2 as detection__v2__pb2


class InstanceDetectionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DetectInstances = channel.unary_unary(
        '/detection_service_v2.InstanceDetectionService/DetectInstances',
        request_serializer=detection__v2__pb2.Image.SerializeToString,
        response_deserializer=detection__v2__pb2.InstanceDetections.FromString,
        )


class InstanceDetectionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DetectInstances(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InstanceDetectionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DetectInstances': grpc.unary_unary_rpc_method_handler(
          servicer.DetectInstances,
          request_deserializer=detection__v2__pb2.Image.FromString,
          response_serializer=detection__v2__pb2.InstanceDetections.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'detection_service_v2.InstanceDetectionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
