# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection_v2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detection_v2.proto',
  package='detection_service_v2',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x64\x65tection_v2.proto\x12\x14\x64\x65tection_service_v2\"S\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\r\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"\xb6\x01\n\x11InstanceDetection\x12\x12\n\nconfidence\x18\x01 \x01(\x02\x12\x10\n\x08label_id\x18\x02 \x01(\r\x12\r\n\x05label\x18\x03 \x01(\t\x12.\n\x03\x62ox\x18\x04 \x01(\x0b\x32!.detection_service_v2.BoundingBox\x12\x11\n\tmask_type\x18\x05 \x01(\x05\x12)\n\x04mask\x18\x06 \x01(\x0b\x32\x1b.detection_service_v2.Image\"R\n\x12InstanceDetections\x12<\n\x0bpredictions\x18\x01 \x03(\x0b\x32\'.detection_service_v2.InstanceDetection2v\n\x18InstanceDetectionService\x12Z\n\x0f\x44\x65tectInstances\x12\x1b.detection_service_v2.Image\x1a(.detection_service_v2.InstanceDetections\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='detection_service_v2.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='detection_service_v2.Image.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='detection_service_v2.Image.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='detection_service_v2.Image.channel', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='detection_service_v2.Image.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='detection_service_v2.Image.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=127,
)


_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='detection_service_v2.BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='detection_service_v2.BoundingBox.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='detection_service_v2.BoundingBox.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='detection_service_v2.BoundingBox.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='detection_service_v2.BoundingBox.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=195,
)


_INSTANCEDETECTION = _descriptor.Descriptor(
  name='InstanceDetection',
  full_name='detection_service_v2.InstanceDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confidence', full_name='detection_service_v2.InstanceDetection.confidence', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_id', full_name='detection_service_v2.InstanceDetection.label_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='detection_service_v2.InstanceDetection.label', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box', full_name='detection_service_v2.InstanceDetection.box', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask_type', full_name='detection_service_v2.InstanceDetection.mask_type', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask', full_name='detection_service_v2.InstanceDetection.mask', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=380,
)


_INSTANCEDETECTIONS = _descriptor.Descriptor(
  name='InstanceDetections',
  full_name='detection_service_v2.InstanceDetections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='predictions', full_name='detection_service_v2.InstanceDetections.predictions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=464,
)

_INSTANCEDETECTION.fields_by_name['box'].message_type = _BOUNDINGBOX
_INSTANCEDETECTION.fields_by_name['mask'].message_type = _IMAGE
_INSTANCEDETECTIONS.fields_by_name['predictions'].message_type = _INSTANCEDETECTION
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['BoundingBox'] = _BOUNDINGBOX
DESCRIPTOR.message_types_by_name['InstanceDetection'] = _INSTANCEDETECTION
DESCRIPTOR.message_types_by_name['InstanceDetections'] = _INSTANCEDETECTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'detection_v2_pb2'
  # @@protoc_insertion_point(class_scope:detection_service_v2.Image)
  ))
_sym_db.RegisterMessage(Image)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDINGBOX,
  __module__ = 'detection_v2_pb2'
  # @@protoc_insertion_point(class_scope:detection_service_v2.BoundingBox)
  ))
_sym_db.RegisterMessage(BoundingBox)

InstanceDetection = _reflection.GeneratedProtocolMessageType('InstanceDetection', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCEDETECTION,
  __module__ = 'detection_v2_pb2'
  # @@protoc_insertion_point(class_scope:detection_service_v2.InstanceDetection)
  ))
_sym_db.RegisterMessage(InstanceDetection)

InstanceDetections = _reflection.GeneratedProtocolMessageType('InstanceDetections', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCEDETECTIONS,
  __module__ = 'detection_v2_pb2'
  # @@protoc_insertion_point(class_scope:detection_service_v2.InstanceDetections)
  ))
_sym_db.RegisterMessage(InstanceDetections)



_INSTANCEDETECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='InstanceDetectionService',
  full_name='detection_service_v2.InstanceDetectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=466,
  serialized_end=584,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectInstances',
    full_name='detection_service_v2.InstanceDetectionService.DetectInstances',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_INSTANCEDETECTIONS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSTANCEDETECTIONSERVICE)

DESCRIPTOR.services_by_name['InstanceDetectionService'] = _INSTANCEDETECTIONSERVICE

# @@protoc_insertion_point(module_scope)
