// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: detection_v2.proto

#include "detection_v2.pb.h"
#include "detection_v2.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace detection_service_v2 {

static const char* InstanceDetectionService_method_names[] = {
  "/detection_service_v2.InstanceDetectionService/DetectInstances",
};

std::unique_ptr< InstanceDetectionService::Stub> InstanceDetectionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InstanceDetectionService::Stub> stub(new InstanceDetectionService::Stub(channel));
  return stub;
}

InstanceDetectionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_DetectInstances_(InstanceDetectionService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InstanceDetectionService::Stub::DetectInstances(::grpc::ClientContext* context, const ::detection_service_v2::Image& request, ::detection_service_v2::InstanceDetections* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DetectInstances_, context, request, response);
}

void InstanceDetectionService::Stub::experimental_async::DetectInstances(::grpc::ClientContext* context, const ::detection_service_v2::Image* request, ::detection_service_v2::InstanceDetections* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DetectInstances_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::detection_service_v2::InstanceDetections>* InstanceDetectionService::Stub::AsyncDetectInstancesRaw(::grpc::ClientContext* context, const ::detection_service_v2::Image& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::detection_service_v2::InstanceDetections>::Create(channel_.get(), cq, rpcmethod_DetectInstances_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::detection_service_v2::InstanceDetections>* InstanceDetectionService::Stub::PrepareAsyncDetectInstancesRaw(::grpc::ClientContext* context, const ::detection_service_v2::Image& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::detection_service_v2::InstanceDetections>::Create(channel_.get(), cq, rpcmethod_DetectInstances_, context, request, false);
}

InstanceDetectionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InstanceDetectionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InstanceDetectionService::Service, ::detection_service_v2::Image, ::detection_service_v2::InstanceDetections>(
          std::mem_fn(&InstanceDetectionService::Service::DetectInstances), this)));
}

InstanceDetectionService::Service::~Service() {
}

::grpc::Status InstanceDetectionService::Service::DetectInstances(::grpc::ServerContext* context, const ::detection_service_v2::Image* request, ::detection_service_v2::InstanceDetections* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace detection_service_v2

