// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: detection_v2.proto

#include "detection_v2.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_detection_5fv2_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_detection_5fv2_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_BoundingBox;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_detection_5fv2_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Image;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_detection_5fv2_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_InstanceDetection;
}  // namespace protobuf_detection_5fv2_2eproto
namespace detection_service_v2 {
class ImageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Image>
      _instance;
} _Image_default_instance_;
class BoundingBoxDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BoundingBox>
      _instance;
} _BoundingBox_default_instance_;
class InstanceDetectionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<InstanceDetection>
      _instance;
} _InstanceDetection_default_instance_;
class InstanceDetectionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<InstanceDetections>
      _instance;
} _InstanceDetections_default_instance_;
}  // namespace detection_service_v2
namespace protobuf_detection_5fv2_2eproto {
static void InitDefaultsImage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::detection_service_v2::_Image_default_instance_;
    new (ptr) ::detection_service_v2::Image();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::detection_service_v2::Image::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Image =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsImage}, {}};

static void InitDefaultsBoundingBox() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::detection_service_v2::_BoundingBox_default_instance_;
    new (ptr) ::detection_service_v2::BoundingBox();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::detection_service_v2::BoundingBox::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BoundingBox =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBoundingBox}, {}};

static void InitDefaultsInstanceDetection() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::detection_service_v2::_InstanceDetection_default_instance_;
    new (ptr) ::detection_service_v2::InstanceDetection();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::detection_service_v2::InstanceDetection::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_InstanceDetection =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsInstanceDetection}, {
      &protobuf_detection_5fv2_2eproto::scc_info_BoundingBox.base,
      &protobuf_detection_5fv2_2eproto::scc_info_Image.base,}};

static void InitDefaultsInstanceDetections() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::detection_service_v2::_InstanceDetections_default_instance_;
    new (ptr) ::detection_service_v2::InstanceDetections();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::detection_service_v2::InstanceDetections::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_InstanceDetections =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsInstanceDetections}, {
      &protobuf_detection_5fv2_2eproto::scc_info_InstanceDetection.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Image.base);
  ::google::protobuf::internal::InitSCC(&scc_info_BoundingBox.base);
  ::google::protobuf::internal::InitSCC(&scc_info_InstanceDetection.base);
  ::google::protobuf::internal::InitSCC(&scc_info_InstanceDetections.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::Image, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::Image, width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::Image, height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::Image, channel_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::Image, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::Image, data_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::Image, rgb_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::BoundingBox, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::BoundingBox, tlx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::BoundingBox, tly_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::BoundingBox, brx_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::BoundingBox, bry_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::InstanceDetection, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::InstanceDetection, confidence_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::InstanceDetection, label_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::InstanceDetection, label_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::InstanceDetection, box_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::InstanceDetection, mask_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::InstanceDetection, mask_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::InstanceDetections, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::detection_service_v2::InstanceDetections, predictions_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::detection_service_v2::Image)},
  { 11, -1, sizeof(::detection_service_v2::BoundingBox)},
  { 20, -1, sizeof(::detection_service_v2::InstanceDetection)},
  { 31, -1, sizeof(::detection_service_v2::InstanceDetections)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::detection_service_v2::_Image_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::detection_service_v2::_BoundingBox_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::detection_service_v2::_InstanceDetection_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::detection_service_v2::_InstanceDetections_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "detection_v2.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022detection_v2.proto\022\024detection_service_"
      "v2\"`\n\005Image\022\r\n\005width\030\001 \001(\r\022\016\n\006height\030\002 \001"
      "(\r\022\017\n\007channel\030\003 \001(\r\022\014\n\004type\030\004 \001(\t\022\014\n\004dat"
      "a\030\005 \001(\014\022\013\n\003rgb\030\006 \001(\010\"A\n\013BoundingBox\022\013\n\003t"
      "lx\030\001 \001(\005\022\013\n\003tly\030\002 \001(\005\022\013\n\003brx\030\003 \001(\005\022\013\n\003br"
      "y\030\004 \001(\005\"\266\001\n\021InstanceDetection\022\022\n\nconfide"
      "nce\030\001 \001(\002\022\020\n\010label_id\030\002 \001(\r\022\r\n\005label\030\003 \001"
      "(\t\022.\n\003box\030\004 \001(\0132!.detection_service_v2.B"
      "oundingBox\022\021\n\tmask_type\030\005 \001(\005\022)\n\004mask\030\006 "
      "\001(\0132\033.detection_service_v2.Image\"R\n\022Inst"
      "anceDetections\022<\n\013predictions\030\001 \003(\0132\'.de"
      "tection_service_v2.InstanceDetection2v\n\030"
      "InstanceDetectionService\022Z\n\017DetectInstan"
      "ces\022\033.detection_service_v2.Image\032(.detec"
      "tion_service_v2.InstanceDetections\"\000b\006pr"
      "oto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 604);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "detection_v2.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_detection_5fv2_2eproto
namespace detection_service_v2 {

// ===================================================================

void Image::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Image::kWidthFieldNumber;
const int Image::kHeightFieldNumber;
const int Image::kChannelFieldNumber;
const int Image::kTypeFieldNumber;
const int Image::kDataFieldNumber;
const int Image::kRgbFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Image::Image()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_detection_5fv2_2eproto::scc_info_Image.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:detection_service_v2.Image)
}
Image::Image(const Image& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.type().size() > 0) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.data().size() > 0) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  ::memcpy(&width_, &from.width_,
    static_cast<size_t>(reinterpret_cast<char*>(&rgb_) -
    reinterpret_cast<char*>(&width_)) + sizeof(rgb_));
  // @@protoc_insertion_point(copy_constructor:detection_service_v2.Image)
}

void Image::SharedCtor() {
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rgb_) -
      reinterpret_cast<char*>(&width_)) + sizeof(rgb_));
}

Image::~Image() {
  // @@protoc_insertion_point(destructor:detection_service_v2.Image)
  SharedDtor();
}

void Image::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Image::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Image::descriptor() {
  ::protobuf_detection_5fv2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detection_5fv2_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Image& Image::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_detection_5fv2_2eproto::scc_info_Image.base);
  return *internal_default_instance();
}


void Image::Clear() {
// @@protoc_insertion_point(message_clear_start:detection_service_v2.Image)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&width_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rgb_) -
      reinterpret_cast<char*>(&width_)) + sizeof(rgb_));
  _internal_metadata_.Clear();
}

bool Image::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:detection_service_v2.Image)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 width = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 height = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 channel = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &channel_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->type().data(), static_cast<int>(this->type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "detection_service_v2.Image.type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes data = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool rgb = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &rgb_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:detection_service_v2.Image)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:detection_service_v2.Image)
  return false;
#undef DO_
}

void Image::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:detection_service_v2.Image)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 width = 1;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->width(), output);
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->height(), output);
  }

  // uint32 channel = 3;
  if (this->channel() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->channel(), output);
  }

  // string type = 4;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detection_service_v2.Image.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->type(), output);
  }

  // bytes data = 5;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->data(), output);
  }

  // bool rgb = 6;
  if (this->rgb() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->rgb(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:detection_service_v2.Image)
}

::google::protobuf::uint8* Image::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:detection_service_v2.Image)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 width = 1;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->width(), target);
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->height(), target);
  }

  // uint32 channel = 3;
  if (this->channel() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->channel(), target);
  }

  // string type = 4;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detection_service_v2.Image.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->type(), target);
  }

  // bytes data = 5;
  if (this->data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->data(), target);
  }

  // bool rgb = 6;
  if (this->rgb() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->rgb(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:detection_service_v2.Image)
  return target;
}

size_t Image::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:detection_service_v2.Image)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string type = 4;
  if (this->type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  // bytes data = 5;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  // uint32 width = 1;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->width());
  }

  // uint32 height = 2;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->height());
  }

  // uint32 channel = 3;
  if (this->channel() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->channel());
  }

  // bool rgb = 6;
  if (this->rgb() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Image::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:detection_service_v2.Image)
  GOOGLE_DCHECK_NE(&from, this);
  const Image* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Image>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:detection_service_v2.Image)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:detection_service_v2.Image)
    MergeFrom(*source);
  }
}

void Image::MergeFrom(const Image& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:detection_service_v2.Image)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.type().size() > 0) {

    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.channel() != 0) {
    set_channel(from.channel());
  }
  if (from.rgb() != 0) {
    set_rgb(from.rgb());
  }
}

void Image::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:detection_service_v2.Image)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Image::CopyFrom(const Image& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:detection_service_v2.Image)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Image::IsInitialized() const {
  return true;
}

void Image::Swap(Image* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Image::InternalSwap(Image* other) {
  using std::swap;
  type_.Swap(&other->type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  data_.Swap(&other->data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(width_, other->width_);
  swap(height_, other->height_);
  swap(channel_, other->channel_);
  swap(rgb_, other->rgb_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Image::GetMetadata() const {
  protobuf_detection_5fv2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detection_5fv2_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void BoundingBox::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BoundingBox::kTlxFieldNumber;
const int BoundingBox::kTlyFieldNumber;
const int BoundingBox::kBrxFieldNumber;
const int BoundingBox::kBryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BoundingBox::BoundingBox()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_detection_5fv2_2eproto::scc_info_BoundingBox.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:detection_service_v2.BoundingBox)
}
BoundingBox::BoundingBox(const BoundingBox& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&tlx_, &from.tlx_,
    static_cast<size_t>(reinterpret_cast<char*>(&bry_) -
    reinterpret_cast<char*>(&tlx_)) + sizeof(bry_));
  // @@protoc_insertion_point(copy_constructor:detection_service_v2.BoundingBox)
}

void BoundingBox::SharedCtor() {
  ::memset(&tlx_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&bry_) -
      reinterpret_cast<char*>(&tlx_)) + sizeof(bry_));
}

BoundingBox::~BoundingBox() {
  // @@protoc_insertion_point(destructor:detection_service_v2.BoundingBox)
  SharedDtor();
}

void BoundingBox::SharedDtor() {
}

void BoundingBox::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BoundingBox::descriptor() {
  ::protobuf_detection_5fv2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detection_5fv2_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BoundingBox& BoundingBox::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_detection_5fv2_2eproto::scc_info_BoundingBox.base);
  return *internal_default_instance();
}


void BoundingBox::Clear() {
// @@protoc_insertion_point(message_clear_start:detection_service_v2.BoundingBox)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&tlx_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&bry_) -
      reinterpret_cast<char*>(&tlx_)) + sizeof(bry_));
  _internal_metadata_.Clear();
}

bool BoundingBox::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:detection_service_v2.BoundingBox)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 tlx = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &tlx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 tly = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &tly_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 brx = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &brx_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 bry = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &bry_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:detection_service_v2.BoundingBox)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:detection_service_v2.BoundingBox)
  return false;
#undef DO_
}

void BoundingBox::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:detection_service_v2.BoundingBox)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 tlx = 1;
  if (this->tlx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->tlx(), output);
  }

  // int32 tly = 2;
  if (this->tly() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->tly(), output);
  }

  // int32 brx = 3;
  if (this->brx() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->brx(), output);
  }

  // int32 bry = 4;
  if (this->bry() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->bry(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:detection_service_v2.BoundingBox)
}

::google::protobuf::uint8* BoundingBox::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:detection_service_v2.BoundingBox)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 tlx = 1;
  if (this->tlx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->tlx(), target);
  }

  // int32 tly = 2;
  if (this->tly() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->tly(), target);
  }

  // int32 brx = 3;
  if (this->brx() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->brx(), target);
  }

  // int32 bry = 4;
  if (this->bry() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->bry(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:detection_service_v2.BoundingBox)
  return target;
}

size_t BoundingBox::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:detection_service_v2.BoundingBox)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 tlx = 1;
  if (this->tlx() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->tlx());
  }

  // int32 tly = 2;
  if (this->tly() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->tly());
  }

  // int32 brx = 3;
  if (this->brx() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->brx());
  }

  // int32 bry = 4;
  if (this->bry() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->bry());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BoundingBox::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:detection_service_v2.BoundingBox)
  GOOGLE_DCHECK_NE(&from, this);
  const BoundingBox* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BoundingBox>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:detection_service_v2.BoundingBox)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:detection_service_v2.BoundingBox)
    MergeFrom(*source);
  }
}

void BoundingBox::MergeFrom(const BoundingBox& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:detection_service_v2.BoundingBox)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.tlx() != 0) {
    set_tlx(from.tlx());
  }
  if (from.tly() != 0) {
    set_tly(from.tly());
  }
  if (from.brx() != 0) {
    set_brx(from.brx());
  }
  if (from.bry() != 0) {
    set_bry(from.bry());
  }
}

void BoundingBox::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:detection_service_v2.BoundingBox)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BoundingBox::CopyFrom(const BoundingBox& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:detection_service_v2.BoundingBox)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BoundingBox::IsInitialized() const {
  return true;
}

void BoundingBox::Swap(BoundingBox* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BoundingBox::InternalSwap(BoundingBox* other) {
  using std::swap;
  swap(tlx_, other->tlx_);
  swap(tly_, other->tly_);
  swap(brx_, other->brx_);
  swap(bry_, other->bry_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BoundingBox::GetMetadata() const {
  protobuf_detection_5fv2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detection_5fv2_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void InstanceDetection::InitAsDefaultInstance() {
  ::detection_service_v2::_InstanceDetection_default_instance_._instance.get_mutable()->box_ = const_cast< ::detection_service_v2::BoundingBox*>(
      ::detection_service_v2::BoundingBox::internal_default_instance());
  ::detection_service_v2::_InstanceDetection_default_instance_._instance.get_mutable()->mask_ = const_cast< ::detection_service_v2::Image*>(
      ::detection_service_v2::Image::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int InstanceDetection::kConfidenceFieldNumber;
const int InstanceDetection::kLabelIdFieldNumber;
const int InstanceDetection::kLabelFieldNumber;
const int InstanceDetection::kBoxFieldNumber;
const int InstanceDetection::kMaskTypeFieldNumber;
const int InstanceDetection::kMaskFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

InstanceDetection::InstanceDetection()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_detection_5fv2_2eproto::scc_info_InstanceDetection.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:detection_service_v2.InstanceDetection)
}
InstanceDetection::InstanceDetection(const InstanceDetection& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.label().size() > 0) {
    label_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.label_);
  }
  if (from.has_box()) {
    box_ = new ::detection_service_v2::BoundingBox(*from.box_);
  } else {
    box_ = NULL;
  }
  if (from.has_mask()) {
    mask_ = new ::detection_service_v2::Image(*from.mask_);
  } else {
    mask_ = NULL;
  }
  ::memcpy(&confidence_, &from.confidence_,
    static_cast<size_t>(reinterpret_cast<char*>(&mask_type_) -
    reinterpret_cast<char*>(&confidence_)) + sizeof(mask_type_));
  // @@protoc_insertion_point(copy_constructor:detection_service_v2.InstanceDetection)
}

void InstanceDetection::SharedCtor() {
  label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&box_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mask_type_) -
      reinterpret_cast<char*>(&box_)) + sizeof(mask_type_));
}

InstanceDetection::~InstanceDetection() {
  // @@protoc_insertion_point(destructor:detection_service_v2.InstanceDetection)
  SharedDtor();
}

void InstanceDetection::SharedDtor() {
  label_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete box_;
  if (this != internal_default_instance()) delete mask_;
}

void InstanceDetection::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* InstanceDetection::descriptor() {
  ::protobuf_detection_5fv2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detection_5fv2_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const InstanceDetection& InstanceDetection::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_detection_5fv2_2eproto::scc_info_InstanceDetection.base);
  return *internal_default_instance();
}


void InstanceDetection::Clear() {
// @@protoc_insertion_point(message_clear_start:detection_service_v2.InstanceDetection)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  label_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && box_ != NULL) {
    delete box_;
  }
  box_ = NULL;
  if (GetArenaNoVirtual() == NULL && mask_ != NULL) {
    delete mask_;
  }
  mask_ = NULL;
  ::memset(&confidence_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&mask_type_) -
      reinterpret_cast<char*>(&confidence_)) + sizeof(mask_type_));
  _internal_metadata_.Clear();
}

bool InstanceDetection::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:detection_service_v2.InstanceDetection)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float confidence = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &confidence_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 label_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &label_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string label = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_label()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->label().data(), static_cast<int>(this->label().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "detection_service_v2.InstanceDetection.label"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .detection_service_v2.BoundingBox box = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_box()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 mask_type = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &mask_type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .detection_service_v2.Image mask = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_mask()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:detection_service_v2.InstanceDetection)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:detection_service_v2.InstanceDetection)
  return false;
#undef DO_
}

void InstanceDetection::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:detection_service_v2.InstanceDetection)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float confidence = 1;
  if (this->confidence() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->confidence(), output);
  }

  // uint32 label_id = 2;
  if (this->label_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->label_id(), output);
  }

  // string label = 3;
  if (this->label().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->label().data(), static_cast<int>(this->label().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detection_service_v2.InstanceDetection.label");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->label(), output);
  }

  // .detection_service_v2.BoundingBox box = 4;
  if (this->has_box()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_box(), output);
  }

  // int32 mask_type = 5;
  if (this->mask_type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->mask_type(), output);
  }

  // .detection_service_v2.Image mask = 6;
  if (this->has_mask()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->_internal_mask(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:detection_service_v2.InstanceDetection)
}

::google::protobuf::uint8* InstanceDetection::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:detection_service_v2.InstanceDetection)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float confidence = 1;
  if (this->confidence() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->confidence(), target);
  }

  // uint32 label_id = 2;
  if (this->label_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->label_id(), target);
  }

  // string label = 3;
  if (this->label().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->label().data(), static_cast<int>(this->label().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "detection_service_v2.InstanceDetection.label");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->label(), target);
  }

  // .detection_service_v2.BoundingBox box = 4;
  if (this->has_box()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_box(), deterministic, target);
  }

  // int32 mask_type = 5;
  if (this->mask_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->mask_type(), target);
  }

  // .detection_service_v2.Image mask = 6;
  if (this->has_mask()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->_internal_mask(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:detection_service_v2.InstanceDetection)
  return target;
}

size_t InstanceDetection::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:detection_service_v2.InstanceDetection)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string label = 3;
  if (this->label().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->label());
  }

  // .detection_service_v2.BoundingBox box = 4;
  if (this->has_box()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *box_);
  }

  // .detection_service_v2.Image mask = 6;
  if (this->has_mask()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *mask_);
  }

  // float confidence = 1;
  if (this->confidence() != 0) {
    total_size += 1 + 4;
  }

  // uint32 label_id = 2;
  if (this->label_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->label_id());
  }

  // int32 mask_type = 5;
  if (this->mask_type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->mask_type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InstanceDetection::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:detection_service_v2.InstanceDetection)
  GOOGLE_DCHECK_NE(&from, this);
  const InstanceDetection* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const InstanceDetection>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:detection_service_v2.InstanceDetection)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:detection_service_v2.InstanceDetection)
    MergeFrom(*source);
  }
}

void InstanceDetection::MergeFrom(const InstanceDetection& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:detection_service_v2.InstanceDetection)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.label().size() > 0) {

    label_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.label_);
  }
  if (from.has_box()) {
    mutable_box()->::detection_service_v2::BoundingBox::MergeFrom(from.box());
  }
  if (from.has_mask()) {
    mutable_mask()->::detection_service_v2::Image::MergeFrom(from.mask());
  }
  if (from.confidence() != 0) {
    set_confidence(from.confidence());
  }
  if (from.label_id() != 0) {
    set_label_id(from.label_id());
  }
  if (from.mask_type() != 0) {
    set_mask_type(from.mask_type());
  }
}

void InstanceDetection::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:detection_service_v2.InstanceDetection)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InstanceDetection::CopyFrom(const InstanceDetection& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:detection_service_v2.InstanceDetection)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstanceDetection::IsInitialized() const {
  return true;
}

void InstanceDetection::Swap(InstanceDetection* other) {
  if (other == this) return;
  InternalSwap(other);
}
void InstanceDetection::InternalSwap(InstanceDetection* other) {
  using std::swap;
  label_.Swap(&other->label_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(box_, other->box_);
  swap(mask_, other->mask_);
  swap(confidence_, other->confidence_);
  swap(label_id_, other->label_id_);
  swap(mask_type_, other->mask_type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata InstanceDetection::GetMetadata() const {
  protobuf_detection_5fv2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detection_5fv2_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void InstanceDetections::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int InstanceDetections::kPredictionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

InstanceDetections::InstanceDetections()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_detection_5fv2_2eproto::scc_info_InstanceDetections.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:detection_service_v2.InstanceDetections)
}
InstanceDetections::InstanceDetections(const InstanceDetections& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      predictions_(from.predictions_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:detection_service_v2.InstanceDetections)
}

void InstanceDetections::SharedCtor() {
}

InstanceDetections::~InstanceDetections() {
  // @@protoc_insertion_point(destructor:detection_service_v2.InstanceDetections)
  SharedDtor();
}

void InstanceDetections::SharedDtor() {
}

void InstanceDetections::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* InstanceDetections::descriptor() {
  ::protobuf_detection_5fv2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detection_5fv2_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const InstanceDetections& InstanceDetections::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_detection_5fv2_2eproto::scc_info_InstanceDetections.base);
  return *internal_default_instance();
}


void InstanceDetections::Clear() {
// @@protoc_insertion_point(message_clear_start:detection_service_v2.InstanceDetections)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  predictions_.Clear();
  _internal_metadata_.Clear();
}

bool InstanceDetections::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:detection_service_v2.InstanceDetections)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .detection_service_v2.InstanceDetection predictions = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_predictions()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:detection_service_v2.InstanceDetections)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:detection_service_v2.InstanceDetections)
  return false;
#undef DO_
}

void InstanceDetections::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:detection_service_v2.InstanceDetections)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .detection_service_v2.InstanceDetection predictions = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->predictions_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->predictions(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:detection_service_v2.InstanceDetections)
}

::google::protobuf::uint8* InstanceDetections::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:detection_service_v2.InstanceDetections)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .detection_service_v2.InstanceDetection predictions = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->predictions_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->predictions(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:detection_service_v2.InstanceDetections)
  return target;
}

size_t InstanceDetections::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:detection_service_v2.InstanceDetections)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .detection_service_v2.InstanceDetection predictions = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->predictions_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->predictions(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InstanceDetections::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:detection_service_v2.InstanceDetections)
  GOOGLE_DCHECK_NE(&from, this);
  const InstanceDetections* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const InstanceDetections>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:detection_service_v2.InstanceDetections)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:detection_service_v2.InstanceDetections)
    MergeFrom(*source);
  }
}

void InstanceDetections::MergeFrom(const InstanceDetections& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:detection_service_v2.InstanceDetections)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  predictions_.MergeFrom(from.predictions_);
}

void InstanceDetections::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:detection_service_v2.InstanceDetections)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InstanceDetections::CopyFrom(const InstanceDetections& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:detection_service_v2.InstanceDetections)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstanceDetections::IsInitialized() const {
  return true;
}

void InstanceDetections::Swap(InstanceDetections* other) {
  if (other == this) return;
  InternalSwap(other);
}
void InstanceDetections::InternalSwap(InstanceDetections* other) {
  using std::swap;
  CastToBase(&predictions_)->InternalSwap(CastToBase(&other->predictions_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata InstanceDetections::GetMetadata() const {
  protobuf_detection_5fv2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_detection_5fv2_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace detection_service_v2
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::detection_service_v2::Image* Arena::CreateMaybeMessage< ::detection_service_v2::Image >(Arena* arena) {
  return Arena::CreateInternal< ::detection_service_v2::Image >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::detection_service_v2::BoundingBox* Arena::CreateMaybeMessage< ::detection_service_v2::BoundingBox >(Arena* arena) {
  return Arena::CreateInternal< ::detection_service_v2::BoundingBox >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::detection_service_v2::InstanceDetection* Arena::CreateMaybeMessage< ::detection_service_v2::InstanceDetection >(Arena* arena) {
  return Arena::CreateInternal< ::detection_service_v2::InstanceDetection >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::detection_service_v2::InstanceDetections* Arena::CreateMaybeMessage< ::detection_service_v2::InstanceDetections >(Arena* arena) {
  return Arena::CreateInternal< ::detection_service_v2::InstanceDetections >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
